### ISSUE TITLE
 java.lang.NullPointerException  at com.rey.material.app.ThemeManager class

### ISSUE THREAD

**Issue by duycm83** [rey5137/material#208] opened 2015-07-31 05:45 UTC
My application is crash when startup.
My App Layout like this:
    <LinearLayout
        android:id="@+id/back"
        style="@style/ListBackContent"
        android:tag="back">
        <com.rey.material.widget.Button
            android:id="@+id/button_bt_flat_color"
            android:layout_width="0dp"
            android:layout_height="@dimen/bt_height"
            android:layout_weight="0.4"
            android:text="BUTTON"
            android:background="@null"
            app:v_styleId="@array/button_flat_color"/>
</LinearLayout>

Would you tell me how to fix below error log.

    java.lang.NullPointerException
            at com.rey.material.app.ThemeManager.registerOnThemeChangedListener(ThemeManager.java:181)
            at com.rey.material.widget.Button.onAttachedToWindow(Button.java:72)
            at android.view.View.dispatchAttachedToWindow(View.java:13522)
            at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2671)
            at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2671)
            at android.view.ViewGroup.addViewInner(ViewGroup.java:3809)
            at android.view.ViewGroup.addViewInLayout(ViewGroup.java:3746)
            at android.widget.ListView.setupChild(ListView.java:1863)
            at android.widget.ListView.makeAndAddView(ListView.java:1816)
            at android.widget.ListView.fillDown(ListView.java:697)
            at android.widget.ListView.fillFromTop(ListView.java:763)
            at android.widget.ListView.layoutChildren(ListView.java:1641)
            at android.widget.AbsListView.onLayout(AbsListView.java:2563)
            at android.view.View.layout(View.java:15762)
            at android.view.ViewGroup.layout(ViewGroup.java:4867)
            at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
            at android.view.View.layout(View.java:15762)
            at android.view.ViewGroup.layout(ViewGroup.java:4867)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
            at android.view.View.layout(View.java:15762)
            at android.view.ViewGroup.layout(ViewGroup.java:4867)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
            at android.view.View.layout(View.java:15762)
            at android.view.ViewGroup.layout(ViewGroup.java:4867)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
            at android.view.View.layout(View.java:15762)
            at android.view.ViewGroup.layout(ViewGroup.java:4867)
            at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2356)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2069)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6637)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:814)
            at android.view.Choreographer.doCallbacks(Choreographer.java:614)
            at android.view.Choreographer.doFrame(Choreographer.java:584)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:800)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5602)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by rey5137** [comment] 2015-08-02 04:07
Which lib version did you use?

**Comment by duycm83** [comment] 2015-08-02 04:13
I used lib version 1.2.1
 compile 'com.github.rey5137:material:1.2.1'

**Comment by swapii** [comment] 2015-08-04 12:24
Catch same exception in my app.

To fix this you need invoke `ThemeManager#init()` method in `Application#onCreate()`:

```java
public class MyApplication extends Application {
    @Override
    public void onCreate() {
        ThemeManager.init(this, 1, 0, null);
    }
}
```

I think this thing must be documented in "Gettings Started" part of docs.

**Comment by qyzhaojinxi** [comment] 2015-08-12 08:10
I have a same problem.I just do it as @swapii  writes.It works.

**Comment by ravib21** [comment] 2015-08-24 08:14
I was facing same issue. @swapii solved my problem.

Thank you! :)

**Comment by asep-ridwan** [comment] 2015-08-30 05:59
i have same case, solved with @swapii solution (sorry for my poor english),
my settings:

    compileSdkVersion 23
    buildToolsVersion "22.0.1"

        minSdkVersion 16

    compile 'com.github.rey5137:material:1.2.1'

**Comment by brunano21** [comment] 2015-09-05 14:20
Ok with swapaii solution, but rendering on Android Studio is still unavailable!

**Comment by lvl4fi4** [comment] 2015-09-13 21:29
solved thanks a lot!

**Comment by brunano21** [comment] 2015-09-13 21:30
Share it

**Comment by lvl4fi4** [comment] 2015-09-13 21:38
android {
        compileSdkVersion 21
        buildToolsVersion "21.1.2"

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
        renderscriptTargetApi 19
        renderscriptSupportModeEnabled true
        }    }


09-14 01:17:14.135    4565-4565/com.devnote E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.devnote/com.devnote.material.demo.MainActivity}: java.lang.NullPointerException
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2343)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2395)
            at android.app.ActivityThread.access$600(ActivityThread.java:162)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
            at android.os.Handler.dispatchMessage(Handler.java:107)
            at android.os.Looper.loop(Looper.java:194)
            at android.app.ActivityThread.main(ActivityThread.java:5371)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
            at com.rey.material.app.ThemeManager.loadStyleList(ThemeManager.java:89)
            at com.rey.material.app.ThemeManager.getStyleList(ThemeManager.java:101)
            at com.rey.material.app.ThemeManager.getStyle(ThemeManager.java:172)
            at com.rey.material.app.ThemeManager.getCurrentStyle(ThemeManager.java:162)
            at com.rey.material.app.ToolbarManager$ThemableNavigationManager.<init>(ToolbarManager.java:534)
            at com.devnote.material.demo.MainActivity$1.<init>(MainActivity.java:68)
            at com.devnote.material.demo.MainActivity.onCreate(MainActivity.java:68)
            at android.app.Activity.performCreate(Activity.java:5122)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1084)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2307)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2395)
            at android.app.ActivityThread.access$600(ActivityThread.java:162)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
            at android.os.Handler.dispatchMessage(Handler.java:107)
            at android.os.Looper.loop(Looper.java:194)
            at android.app.ActivityThread.main(ActivityThread.java:5371)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
            at dalvik.system.NativeStart.main(Native Method)


JUST SOLVED BY  @swapii's solution


		@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
        ThemeManager.init(this, 1, 0, null);
		setContentView(R.layout.rd_activity_main);

**Comment by lvl4fi4** [comment] 2015-09-13 22:32
Agreed with @brunano21 , still having render problem!

**Comment by lvl4fi4** [comment] 2015-09-14 10:38
@brunano21 i just did a trick for rendering problem .
check if may helps you too!
https://github.com/rey5137/material/issues/217

**Comment by rey5137** [comment] 2015-12-11 04:28
Duplicate of #217

**Closed by rey5137** 2015-12-11 04:28 UTC
