### ISSUE TITLE
Problem in Demo app

### ISSUE THREAD

**Issue by enginebai** [rey5137/material#6] opened 2015-03-29 01:37 UTC
Hi, I've installed the Demo app, but some problem happened.
1. In Android 5.0, all the text in dialog vanish, but it's OK in 4.4 (you can check the following 2nd photo)
![11096938_943655545679951_2108684416_o jpg](https://cloud.githubusercontent.com/assets/3387462/6883740/f2750648-d5f6-11e4-90dc-77765787e102.png)

2. In Android 4.4, the button in actionbar vanishes (in my case, it's refresh button), it's find in 5.0.
![11028656_943655905679915_139509241_o jpg](https://cloud.githubusercontent.com/assets/3387462/6883739/da1ab3ea-d5f6-11e4-86c5-804e13e666f0.png)

I think this may be the theme or style problem. Thank you again.

**Comment by rey5137** [comment] 2015-04-01 05:39
I have tested the demo app on emulator 5.0 and all dialog is styled correctly. Can you please provide some details about your devices?

**Comment by enginebai** [comment] 2015-04-01 06:45
My device are HTC One 801e (M7) phone, Android 5.0.2. and Nexus 5.0 emulator, Android 5.0.0.
All the text is not styled correctly in my all devices.

**Comment by apat183** [comment] 2015-04-01 13:48
I'm also getting the issue for no content showing on dialogs for demo app. Moto x 2014 running 5.0.

**Comment by yogeshmadaan100** [comment] 2015-04-02 05:48
Is this issue open. As it working fine on 5.1. Tested on Nexus 5

**Comment by rey5137** [comment] 2015-04-02 05:54
Yes, it's still open. I just don't have any way to obtain a real 5.0 devices to test it. I tested it on emulator 5.0 and it work fine (somehow genymotion 5.0 devices doesn't boot up on my pc).

**Comment by yogeshmadaan100** [comment] 2015-04-02 05:57
These are the screenshots for more understanding. I didn't found any issues in it.

![screenshot_2015-04-02-11-24-58](https://cloud.githubusercontent.com/assets/7336772/6958542/2d725a0c-d92b-11e4-9618-e231bd993ac9.png)
![screenshot_2015-04-02-11-24-53](https://cloud.githubusercontent.com/assets/7336772/6958543/2d75d290-d92b-11e4-95f2-39bf021e84de.png)

**Comment by enginebai** [comment] 2015-04-02 07:26
I think that the problem is the colors in system theme vary after android 5.0, I found some default color will reverse in android 5.0 (such as it is black text in android 4.4, but it is white text in android 5.0).

I will try to replace the color with real color code rather than the value ref to system theme.
Report here if the issue is fixed then.

**Comment by rey5137** [comment] 2015-04-02 18:26
Seem like the cause of this bug is passing 0 as second parameter of Dialog's super constructor call. Here is a [fixed version](https://www.dropbox.com/s/71nzt9dey6zvj7s/material_debug_04032015.apk). Can you try it on real device and let me know the result. I can only test it on genymotion 5.0 devices.

**Comment by yogeshmadaan100** [comment] 2015-04-02 18:41
Parse Error @rey5137

**Comment by apat183** [comment] 2015-04-02 18:45
Can confirm the updated version posted is working perfectly fine on moto x
2014 with android 5.0

**Comment by rey5137** [comment] 2015-04-03 02:16
@yogeshmadaan100 Did you mean parsing error when you install apk? The apk is debug version, so the SHA-1 is different with the release version. You should uninstall the app before install it.

**Comment by enginebai** [comment] 2015-04-03 02:16
The fixed version works fine!!!

**Comment by inteist** [comment] 2015-04-03 02:39
Here's a short link for convenience: http://bit.ly/mdialogL
I can confirm that the demo app is working on Nexus 4 with L

**However... ** the fix doesn't seem to be in the codebase as I have updated the repo to the most recent commit on the `dev` branch where I reported the bug in #19

**Comment by major-laslo** [comment] 2015-04-03 08:03
Also confirming it works fine on Nexus 5 with 5.1, nice.

**Comment by enginebai** [comment] 2015-04-03 14:53
This fixed version works fine on my HTC M7 devices, nice job.

**Comment by rey5137** [comment] 2015-04-03 15:26
Ok, then I'll close this issue.

**Closed by rey5137** 2015-04-03 15:26 UTC
Labels: bug

**Comment by inteist** [comment] 2015-04-03 15:50
Please merge the fixes into the library.  As I mentioned, I have updated the repo to the most recent commit on the dev branch but the problem exists there.

**Comment by inteist** [comment] 2015-04-03 16:03
Would be great if you could update the library on maven ASAP so we can use the fixed version in our projects. Appreciate the quick fixes.

**Comment by rey5137** [comment] 2015-04-03 17:06
I will update in next day. For now you can try 1.01-SNAPSHOT version.

**Comment by inteist** [comment] 2015-04-03 20:03
I was wondering why isn't the "native" picker used if it is L ? Makes sense to use the "native" component if it is available. This is what Google usually does in the compat libs. Only has custom implementation if it is not supported natively by the OS already. Would also avoid this problem.
