### ISSUE TITLE
How could I cast edittext inside a custom Dialog?

### ISSUE THREAD

**Issue by RenatoZevallos** [rey5137/material#97] opened 2015-05-12 23:21 UTC
Hi,

I'm trying to set and get (later) the text from a EditText inside a Custom Dialog. I'm trying to cast it like this:

    //region SET TAG
        final TextView alarm_tag = (TextView) convertView.findViewById(R.id.tag_text);
        alarm_tag.setText(alarms.get(position).alarm_name);
        alarm_tag.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Dialog.Builder builder;
                builder = new SimpleDialog.Builder(R.style.SimpleDialog){
                    @Override
                    protected Dialog onBuild(Context context, int styleId) {
                        Dialog dialog = super.onBuild(context, styleId);
                        dialog.layoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT);

                        editText = (EditText) dialog.findViewById(R.id.txtEditTag);
                        String oldTag = helper.getAlarmTag(alarmas.get(position).alarma_id);
                        Log.d("AlarmAdapter", "oldTag = " + oldTag);
                        editText.setText(oldTag);

                        return dialog;
                    }

                    @Override
                    public void onPositiveActionClicked(DialogFragment fragment) {
                        String newTag = editText.getText().toString();
                        helper.updateAlarmTag(alarmas.get(position).alarma_id, newTag);
                        super.onPositiveActionClicked(fragment);
                    }

                    @Override
                    public void onNegativeActionClicked(DialogFragment fragment) {
                        Toast.makeText(fragment.getDialog().getContext(), "Cancelled", Toast.LENGTH_SHORT).show();
                        super.onNegativeActionClicked(fragment);
                    }
                };

                builder.title(context.getString(R.string.txtTagEdit))
                        .positiveAction("SAVE")
                        .negativeAction("CANCEL")
                        .contentView(R.layout.layout_dialog_tag);

                DialogFragment fragment = DialogFragment.newInstance(builder);
                fragment.show(fragmentManager, null);
            }
        });
        //endregion

But it gaves me an error like my EditText wasn't initialized.

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.rey.material.widget.EditText.setText(java.lang.CharSequence)' on a null object reference
            at com.rzr.rzevallosr.miappdepruebas.AlarmAdapter$3$1.onBuild(AlarmAdapter.java:201)
            at com.rey.material.app.Dialog$Builder.build(Dialog.java:1020)

Thanks for your time and help.

Regards.

**Comment by rey5137** [comment] 2015-05-13 02:21
Duplicate of #59

**Closed by rey5137** 2015-05-13 02:21 UTC
