### ISSUE TITLE
demo crashes on date picker dialogs

### ISSUE THREAD

**Issue by ThanosFisherman** [rey5137/material#26] opened 2015-04-06 22:55 UTC
Hey,
I just discovered this neat library. Just letting you know that demo app on play store crashes when i click on either of the 2 date picker buttons (date light and date dark buttons) You may want to check it out.
I'm using lg g pad 8.3 tablet android 4.4.2

**Comment by rey5137** [comment] 2015-04-07 02:46
Duplicate of #7

**Closed by rey5137** 2015-04-07 02:46 UTC
Labels: duplicate
