### ISSUE TITLE
DatePicker dialog is blank in OS > L (5.+)

### ISSUE THREAD

**Issue by inteist** [rey5137/material#19] opened 2015-04-02 23:35 UTC
![](http://i.imgur.com/CDglIqJ.png)

**Comment by rey5137** [comment] 2015-04-03 02:02
Duplicate of #6.

**Comment by inteist** [comment] 2015-04-03 02:20
I checked out the most recent `dev` branch which has a comment that it is supposed to fix that but it doesn't.

**Comment by rey5137** [comment] 2015-04-03 02:28
Please comment on #6 so everyone can follow. Did you already test the fixed apk I upload?

**Closed** 2015-04-04 08:42 UTC
Labels: duplicate
