### ISSUE TITLE
java.lang.NoSuchFieldError: com.rey.material.R$styleable.Spinner_android_gravity

### ISSUE THREAD

**Issue by grevolution** [rey5137/material#243] opened 2015-09-09 06:58 UTC
I am getting following exception when I am using spinner:

` java.lang.NoSuchFieldError: com.rey.material.R$styleable.Spinner_android_gravity`

I am using the spinner like this:

```
    <com.rey.material.widget.Spinner
        android:id="@+id/sp_sms_frequency"
        style="@style/Material.Widget.Spinner" android:layout_below="@+id/tx_title_sms_freq"
        android:layout_width="match_parent" android:layout_marginLeft="@dimen/activity_horizontal_margin_32"
        android:layout_height="wrap_content"  android:layout_marginRight="@dimen/activity_horizontal_margin_32"
        app:rd_style="@style/Material.Drawable.Ripple.Wave"
        app:spn_labelEnable="true"
        app:spn_label="@string/ceq_settings_select_sms"
        />
```

**Comment by aumidbek** [comment] 2015-09-10 17:53
If you use com.android.support:appcompat-v7:23+, solution for this error described in this [issue](https://github.com/rey5137/material/issues/222).

@adityanaik says:
Open build.gradle (Module: app)

Change `compile 'com.github.rey5137:material:1.2.1'`
to `compile 'com.github.rey5137:material:1.2.1.6-SNAPSHOT'`

Then after `apply plugin: 'com.android.application'` , put
`repositories { maven { url "https://oss.sonatype.org/content/repositories/snapshots" } }`

Then make a Gradle sync as suggested by Android Studio.

Found the answer here http://stackoverflow.com/questions/20574111/add-maven-repository-to-build-gradle

Hope this helps!

**Comment by rey5137** [comment] 2015-09-12 03:04
Duplicate of #222

**Closed by rey5137** 2015-09-12 03:04 UTC
