### ISSUE TITLE
layouts could not rendered

### ISSUE THREAD

**Issue by saeed-zh** [rey5137/material#262] opened 2015-09-22 06:22 UTC
I have used theme manager property in my app, from 2 days age when I open any layout xml, it could not rendered, and show me below exception. I have no change in my codes from 2 days ago and at that time layouts were displayed. please help

java.lang.NullPointerException
	at com.rey.material.app.ThemeManager.registerOnThemeChangedListener(ThemeManager.java:181)
	at com.rey.material.widget.EditText.onAttachedToWindow(EditText.java:469)
	at android.view.View.dispatchAttachedToWindow(View.java:14514)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2836)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2843)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2843)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2843)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2843)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2843)
	at android.view.AttachInfo_Accessor.setAttachInfo(AttachInfo_Accessor.java:42)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:232)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:426)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:350)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:511)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:499)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:888)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:499)
	at com.android.tools.idea.rendering.RenderTask.access$600(RenderTask.java:72)
	at com.android.tools.idea.rendering.RenderTask$3.call(RenderTask.java:611)
	at com.android.tools.idea.rendering.RenderTask$3.call(RenderTask.java:608)
	at com.android.tools.idea.rendering.RenderService.runRenderAction(RenderService.java:365)
	at com.android.tools.idea.rendering.RenderTask.render(RenderTask.java:608)
	at com.android.tools.idea.rendering.RenderTask.render(RenderTask.java:630)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager.doRender(AndroidLayoutPreviewToolWindowManager.java:643)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager.access$1700(AndroidLayoutPreviewToolWindowManager.java:80)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager$7$1.run(AndroidLayoutPreviewToolWindowManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager$7.run(AndroidLayoutPreviewToolWindowManager.java:580)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
	at com.intellij.util.ui.update.MergingUpdateQueue$2.run(MergingUpdateQueue.java:254)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:269)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:227)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:217)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by saeed-zh** [comment] 2015-09-22 06:26
application works fine at runtime, but i can not see changes visually when I change my xml code. this is on of those layout xml


    <?xml version="1.0" encoding="utf-8"?>
    <ScrollView xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:tools="http://schemas.android.com/tools"
       android:layout_width="match_parent"
       android:layout_height="match_parent"
       xmlns:app="http://schemas.android.com/apk/res-auto"
       android:orientation="horizontal"
       android:scrollbars="none"
       android:weightSum="1"
       tools:ignore="DisableBaselineAlignment">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginLeft="15dp"
        android:layout_marginRight="15dp"
        android:layout_marginTop="20dp"
        android:orientation="vertical"
        android:weightSum="10" >

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:layout_weight="8"
            android:orientation="vertical" >

            <specialComponent.DavatFontAutoCompleteTextView
                android:id="@+id/bankInsertNameDavatFontAutoCompleteTextView"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:ems="10"
                android:hint="@string/bankInsertName"
                android:inputType="textPersonName"
                app:et_inputId="@+id/input11"
                app:et_supportMode="none"
                app:v_styleId="@array/EditText"
                app:et_autoCompleteMode="single" />

            <specialComponent.DavatFontEditText
                android:id="@+id/bankInsertPadroneNameDavatFontEditText"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:ems="10"
                android:hint="@string/bankInsertPadroneName"
                android:inputType="textPersonName"
                app:et_inputId="@+id/input1"
                app:et_supportMode="none"
                app:v_styleId="@array/EditText"/>

            <specialComponent.DavatFontEditText
                android:id="@+id/bankInsertSubStationNameDavatFontEditText"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:ems="10"
                android:hint="@string/bankInsertSubStationName"
                android:inputType="textPersonName"
                app:et_inputId="@+id/input2"
                app:et_supportMode="none"
                app:v_styleId="@array/EditText"/>

            <specialComponent.DavatFontEditText
                android:id="@+id/bankInsertAccountNumberDavatFontEditText"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:ems="10"
                android:hint="@string/bankInsertAccountNumber"
                android:inputType="number"
                app:et_inputId="@+id/input3"
                app:et_supportMode="none"
                app:v_styleId="@array/EditText" />

            <specialComponent.DavatFontEditText
                android:id="@+id/bankInsertCardNumberDavatFontEditText"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:ems="10"
                android:hint="@string/bankInsertCardNumber"
                android:inputType="number"
                app:et_inputId="@+id/input4"
                app:et_supportMode="none"
                app:v_styleId="@array/EditText" />

            <specialComponent.DavatFontEditText
                android:id="@+id/bankInsertAddressDavatFontEditText"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:ems="10"
                android:hint="@string/bankInsertAddress"
                android:inputType="textPostalAddress"
                app:et_inputId="@+id/input5"
                app:et_supportMode="none"
                app:v_styleId="@array/EditText" />

            <specialComponent.DavatFontEditText
                android:id="@+id/bankInsertPhoneNumberDavatFontEditText"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:ems="10"
                android:hint="@string/bankInsertPhoneNumber"
                android:inputType="phone"
                app:et_inputId="@+id/input6"
                app:et_supportMode="none"
                app:v_styleId="@array/EditText" />

            <include
                layout="@layout/information_insert_bottom_part"
                />

        </LinearLayout>
	
		<specialComponent.DavatFontButton
		    android:id="@+id/bankInsertSaveInformationDavatFontButton"
		    style="?android:attr/buttonStyleSmall"
            app:v_styleId="@array/Button_Rectangle"
		    android:layout_width="match_parent"
		    android:layout_height="wrap_content"
            android:layout_margin="5dp"
		    android:text="@string/save" />
		
	</LinearLayout>
	
</ScrollView>

**Comment by saeed-zh** [comment] 2015-09-22 09:59
I found solution. see #217 thanks @lvl4fi4

**Comment by lvl4fi4** [comment] 2015-09-22 10:02
your must welcome @saeed-zh khan!

**Comment by rey5137** [comment] 2015-12-11 04:28
Duplicate of #217

**Closed by rey5137** 2015-12-11 04:28 UTC
